name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:    
       - name: Checkout
         uses: actions/checkout@v2
       - name: alire-project/setup-alire
         uses: alire-project/setup-alire@latest-devel
       - name: Build
         run: |
          alr index --reset-community
          alr toolchain --select gnat_native --non-interactive --disable-assistant
          alr toolchain --select gprbuild --non-interactive --disable-assistant
          alr build --non-interactive
