name: Latest Artifacts

on:
  schedule:
    - cron: '30 23 * * *'
      timezone: "America/New_York"
  workflow_dispatch: # Allows manual override

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: septum-linux-x86_64
            binary_path: septum/bin/septum
          - os: macos-latest
            artifact_name: septum-macos-arm64
            binary_path: septum/bin/septum
          - os: windows-latest
            artifact_name: septum-windows-x86_64
            binary_path: septum/bin/septum.exe

    steps:
      - name: Checkout Septum
        uses: actions/checkout@v6
        with:
          path: septum

      - name: Setup Alire
        uses: alire-project/setup-alire@1ff7d9224297858cc9ecce29b08bc6109f93e49a

      - name: Build project
        working-directory: septum
        run: alr build --release
        env:
          SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
          LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib

      - name: Prepare Artifact Folder
        shell: bash
        run: |
          mkdir -p dist
          cp ${{ matrix.binary_path }} dist/
          cp septum/LICENSE dist/ || true
          cp septum/README.md dist/ || true

      - name: Upload Platform Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/*
          retention-days: 1
