name: Build

on:
  push:
    branches: [ main, gh-actions ]
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout Septum
        uses: actions/checkout@v6
        with:
          path: septum

      - name: Setup Alire
        uses: alire-project/setup-alire@1ff7d9224297858cc9ecce29b08bc6109f93e49a
        with:
          version: 2.1.0

      - name: Build project
        working-directory: septum
        run: alr build --release

      - name: Unit Tests
        working-directory: septum/tests/
        run: |
          alr --no-tty build
